//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurplePen {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscText() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurplePen.MiscText", typeof(MiscText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the appearance of the ellipse. After pressing OK, drag the mouse to place the ellipse in the desired location..
        /// </summary>
        internal static string AddEllipseExplanation {
            get {
                return ResourceManager.GetString("AddEllipseExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Ellipse.
        /// </summary>
        internal static string AddEllipseTitle {
            get {
                return ResourceManager.GetString("AddEllipseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the appearance of the line. After pressing OK, drag the mouse to draw the line segments in the desired location..
        /// </summary>
        internal static string AddLineExplanation {
            get {
                return ResourceManager.GetString("AddLineExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Line.
        /// </summary>
        internal static string AddLineTitle {
            get {
                return ResourceManager.GetString("AddLineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Set the appearance of the rectangle. After pressing OK, drag the mouse to place the rectangle in the desired location..
        /// </summary>
        internal static string AddRectangleExplanation {
            get {
                return ResourceManager.GetString("AddRectangleExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Rectangle.
        /// </summary>
        internal static string AddRectangleTitle {
            get {
                return ResourceManager.GetString("AddRectangleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter the text you wish to place on the map. After pressing OK, drag the mouse to place the text in the desired location..
        /// </summary>
        internal static string AddTextSpecialExplanation {
            get {
                return ResourceManager.GetString("AddTextSpecialExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Add Text.
        /// </summary>
        internal static string AddTextSpecialTitle {
            get {
                return ResourceManager.GetString("AddTextSpecialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All controls.
        /// </summary>
        internal static string AllControls {
            get {
                return ResourceManager.GetString("AllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All Parts.
        /// </summary>
        internal static string AllParts {
            get {
                return ResourceManager.GetString("AllParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All Variations.
        /// </summary>
        internal static string AllVariations {
            get {
                return ResourceManager.GetString("AllVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a course setting for orienteering.
        /// </summary>
        internal static string AppSubtitle {
            get {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Purple Pen.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Automatic.
        /// </summary>
        internal static string AutomaticLength {
            get {
                return ResourceManager.GetString("AutomaticLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The climb for a course must be a number 0-9999, or blank..
        /// </summary>
        internal static string BadClimb {
            get {
                return ResourceManager.GetString("BadClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The  .NET framework on your computer does not appear to be correctly installed. Please visit http://microsoft.com/net and install the latest version of the .NET framework for your Windows operating system..
        /// </summary>
        internal static string BadDotNetFramework {
            get {
                return ResourceManager.GetString("BadDotNetFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &apos;{0}&apos; is not a valid leg number for branch &apos;{1}&apos;.
        /// </summary>
        internal static string BadLegNumber {
            get {
                return ResourceManager.GetString("BadLegNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The length for a course must be a number 0.1 - 99.9, or blank to calculate length automatically..
        /// </summary>
        internal static string BadLength {
            get {
                return ResourceManager.GetString("BadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The load for a course must be an integer 0-999999, or blank..
        /// </summary>
        internal static string BadLoad {
            get {
                return ResourceManager.GetString("BadLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The print scale must be a number between 100 and 100,000..
        /// </summary>
        internal static string BadScale {
            get {
                return ResourceManager.GetString("BadScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The points for a control must be an integer 1-999..
        /// </summary>
        internal static string BadScore {
            get {
                return ResourceManager.GetString("BadScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The underlying OCAD map has visible template files. In OCAD 8 and below, these templates may not appear due to limitations in OCAD..
        /// </summary>
        internal static string BaseMapHasVisibleTemplatesThatMayNotAppear {
            get {
                return ResourceManager.GetString("BaseMapHasVisibleTemplatesThatMayNotAppear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancelled by user.
        /// </summary>
        internal static string CancelledByUser {
            get {
                return ResourceManager.GetString("CancelledByUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel Operation.
        /// </summary>
        internal static string CancelOperation {
            get {
                return ResourceManager.GetString("CancelOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ca&amp;ncel Operation.
        /// </summary>
        internal static string CancelOperationWithShortcut {
            get {
                return ResourceManager.GetString("CancelOperationWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descriptions may not be added to a course with a map exchange if &quot;All Parts&quot; is being displayed. Switch to the part you wish to add descriptions to, and then choose &quot;Add Descriptions&quot; again..
        /// </summary>
        internal static string CannotAddDescriptionsToAllParts {
            get {
                return ResourceManager.GetString("CannotAddDescriptionsToAllParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot add variation..
        /// </summary>
        internal static string CannotAddVariation {
            get {
                return ResourceManager.GetString("CannotAddVariation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Error during CSV export.
        /// </summary>
        internal static string CannotCreateCSV {
            get {
                return ResourceManager.GetString("CannotCreateCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot create folder &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotCreateDirectory {
            get {
                return ResourceManager.GetString("CannotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot create &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotCreateFile {
            get {
                return ResourceManager.GetString("CannotCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot create image files for the following reason:.
        /// </summary>
        internal static string CannotCreateImageFiles {
            get {
                return ResourceManager.GetString("CannotCreateImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot create OCAD files for the following reason:.
        /// </summary>
        internal static string CannotCreateOcadFiles {
            get {
                return ResourceManager.GetString("CannotCreateOcadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot create PDFs for the following reason:.
        /// </summary>
        internal static string CannotCreatePdfs {
            get {
                return ResourceManager.GetString("CannotCreatePdfs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot load &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotLoadFile {
            get {
                return ResourceManager.GetString("CannotLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot load map file &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotLoadMapFile {
            get {
                return ResourceManager.GetString("CannotLoadMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot print &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotPrint {
            get {
                return ResourceManager.GetString("CannotPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot read image file &apos;{0}&apos;..
        /// </summary>
        internal static string CannotReadImageFile {
            get {
                return ResourceManager.GetString("CannotReadImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot read map for the following reason: &apos;{0}&apos; Using Optimize/Repair and re-saving in OCAD may fix problems..
        /// </summary>
        internal static string CannotReadMap {
            get {
                return ResourceManager.GetString("CannotReadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot read map for the following reason: &apos;{0}&apos; Opening and re-saving the map in the latest version of OpenOrienteering Mapper may fix problems..
        /// </summary>
        internal static string CannotReadMapOOM {
            get {
                return ResourceManager.GetString("CannotReadMapOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cannot save &apos;{0}&apos; for the following reason:.
        /// </summary>
        internal static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control that starts a fork or loop cannot be dragged to a new place in the course..
        /// </summary>
        internal static string CantRearrangeSplitControl {
            get {
                return ResourceManager.GetString("CantRearrangeSplitControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The current event has textual control descriptions in {0}. Would you like to change the language of control descriptions to {1}?.
        /// </summary>
        internal static string ChangeDescriptionLanguage {
            get {
                return ResourceManager.GetString("ChangeDescriptionLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change the appearance of the line or rectangle..
        /// </summary>
        internal static string ChangeLineAppearanceExplanation {
            get {
                return ResourceManager.GetString("ChangeLineAppearanceExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change Line Appearance.
        /// </summary>
        internal static string ChangeLineAppearanceTitle {
            get {
                return ResourceManager.GetString("ChangeLineAppearanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter the new text..
        /// </summary>
        internal static string ChangeTextSpecialExplanation {
            get {
                return ResourceManager.GetString("ChangeTextSpecialExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Change Text.
        /// </summary>
        internal static string ChangeTextTitle {
            get {
                return ResourceManager.GetString("ChangeTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Choose Color....
        /// </summary>
        internal static string ChooseOtherColor {
            get {
                return ResourceManager.GetString("ChooseOtherColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Clear Selection.
        /// </summary>
        internal static string ClearSelectionWithShortcut {
            get {
                return ResourceManager.GetString("ClearSelectionWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Purple Pen must be closed before loading the created OCAD files..
        /// </summary>
        internal static string ClosePPBeforeLoadingOCAD {
            get {
                return ResourceManager.GetString("ClosePPBeforeLoadingOCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control code must be one, two, or three letters or digits..
        /// </summary>
        internal static string CodeBadLength {
            get {
                return ResourceManager.GetString("CodeBadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control code should not begin with zero..
        /// </summary>
        internal static string CodeBeginsWithZero {
            get {
                return ResourceManager.GetString("CodeBeginsWithZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control code must not contain a space..
        /// </summary>
        internal static string CodeContainsSpace {
            get {
                return ResourceManager.GetString("CodeContainsSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control code should not look like another number when upside-down..
        /// </summary>
        internal static string CodeCouldBeUpsideDown {
            get {
                return ResourceManager.GetString("CodeCouldBeUpsideDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The control code &apos;{0}&apos; is already used by another control..
        /// </summary>
        internal static string CodeInUse {
            get {
                return ResourceManager.GetString("CodeInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Control {0}.
        /// </summary>
        internal static string Control_Code {
            get {
                return ResourceManager.GetString("Control_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Course Properties.
        /// </summary>
        internal static string CoursePropertiesTitle {
            get {
                return ResourceManager.GetString("CoursePropertiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancel.
        /// </summary>
        internal static string CrashCancel {
            get {
                return ResourceManager.GetString("CrashCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Contact Email.
        /// </summary>
        internal static string CrashEmail {
            get {
                return ResourceManager.GetString("CrashEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a An error has occurred. In order to help us fix the problem, please enter your email address and additional information, and send us an error report..
        /// </summary>
        internal static string CrashIntro {
            get {
                return ResourceManager.GetString("CrashIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Please tell us what you were doing in the program, to help fix the problem.
        /// </summary>
        internal static string CrashMessage {
            get {
                return ResourceManager.GetString("CrashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Save.
        /// </summary>
        internal static string CrashSave {
            get {
                return ResourceManager.GetString("CrashSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Send Report.
        /// </summary>
        internal static string CrashSend {
            get {
                return ResourceManager.GetString("CrashSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Create PDF.
        /// </summary>
        internal static string CreatePdf {
            get {
                return ResourceManager.GetString("CreatePdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creating {0}....
        /// </summary>
        internal static string CreatingFile {
            get {
                return ResourceManager.GetString("CreatingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CSV |*.csv.
        /// </summary>
        internal static string CSVFilter {
            get {
                return ResourceManager.GetString("CSVFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ctrl+Y.
        /// </summary>
        internal static string CtrlY {
            get {
                return ResourceManager.GetString("CtrlY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ctrl+Z.
        /// </summary>
        internal static string CtrlZ {
            get {
                return ResourceManager.GetString("CtrlZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Custom Color.
        /// </summary>
        internal static string CustomColor {
            get {
                return ResourceManager.GetString("CustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dark Blue.
        /// </summary>
        internal static string DarkBlue {
            get {
                return ResourceManager.GetString("DarkBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Control {0} is currently used by the following courses: {1}. Do you want to delete this control anyway?.
        /// </summary>
        internal static string DeleteControlFromAllControls {
            get {
                return ResourceManager.GetString("DeleteControlFromAllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Control {0} is no longer used by any course. Do you want to delete this control from the control collection?.
        /// </summary>
        internal static string DeleteControlFromControlsCollection {
            get {
                return ResourceManager.GetString("DeleteControlFromControlsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Controls {0} are no longer used by any course. Do you want to delete these controls from the control collection?.
        /// </summary>
        internal static string DeleteMultipleControlsFromControlsCollection {
            get {
                return ResourceManager.GetString("DeleteMultipleControlsFromControlsCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The code &quot;{0}&quot; is used more than once..
        /// </summary>
        internal static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duplicate Course.
        /// </summary>
        internal static string DuplicateCourseTitle {
            get {
                return ResourceManager.GetString("DuplicateCourseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new climb in meters.
        /// </summary>
        internal static string EnterClimb {
            get {
                return ResourceManager.GetString("EnterClimb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new code.
        /// </summary>
        internal static string EnterCode {
            get {
                return ResourceManager.GetString("EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new course name.
        /// </summary>
        internal static string EnterCourseName {
            get {
                return ResourceManager.GetString("EnterCourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter feature size
        ///Use / for height on a slope
        ///Use | for two features.
        /// </summary>
        internal static string EnterDimensions {
            get {
                return ResourceManager.GetString("EnterDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new event title
        ///Use | to separate lines
        ///(affects all courses).
        /// </summary>
        internal static string EnterEventTitle {
            get {
                return ResourceManager.GetString("EnterEventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter length in km, or leave blank to calculate automatically.
        /// </summary>
        internal static string EnterLength {
            get {
                return ResourceManager.GetString("EnterLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new score.
        /// </summary>
        internal static string EnterScore {
            get {
                return ResourceManager.GetString("EnterScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new secondary title
        ///Use | to separate lines.
        /// </summary>
        internal static string EnterSecondaryTitle {
            get {
                return ResourceManager.GetString("EnterSecondaryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new symbol meaning
        ///(affects all courses).
        /// </summary>
        internal static string EnterSymbolText {
            get {
                return ResourceManager.GetString("EnterSymbolText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Enter new text
        ///Use | to separate lines.
        /// </summary>
        internal static string EnterTextLine {
            get {
                return ResourceManager.GetString("EnterTextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esc.
        /// </summary>
        internal static string Esc {
            get {
                return ResourceManager.GetString("Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File &apos;{0}&apos; already exists in the specified folder. Click the &quot;Back&quot; button and choose a new folder or a new event title..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finish.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a F.
        /// </summary>
        internal static string Finish_Short {
            get {
                return ResourceManager.GetString("Finish_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Finish.
        /// </summary>
        internal static string FinishButtonText {
            get {
                return ResourceManager.GetString("FinishButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Suitable for use in relays with {0} participants per team..
        /// </summary>
        internal static string ForkSummary {
            get {
                return ResourceManager.GetString("ForkSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The map file must be an OCAD file to use GPX files..
        /// </summary>
        internal static string GpxMustBeOcadMap {
            get {
                return ResourceManager.GetString("GpxMustBeOcadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The OCAD file must have a coordinate system defined to use GPX files..
        /// </summary>
        internal static string GpxMustHaveCoordSystem {
            get {
                return ResourceManager.GetString("GpxMustHaveCoordSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The OCAD file must have real world coordinates defined to use GPX files..
        /// </summary>
        internal static string GpxMustHaveRealWorldCoord {
            get {
                return ResourceManager.GetString("GpxMustHaveRealWorldCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Could not reproject points; either the coordinate system or the real world coordinates in the OCAD map are wrong..
        /// </summary>
        internal static string GpxReprojectFailure {
            get {
                return ResourceManager.GetString("GpxReprojectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The OCAD file uses a coordinate system that is not supported by Purple Pen..
        /// </summary>
        internal static string GpxUnsupportedCoordSystem {
            get {
                return ResourceManager.GetString("GpxUnsupportedCoordSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Help file &apos;{0}&apos; could not be opened..
        /// </summary>
        internal static string HelpFileNotFound {
            get {
                return ResourceManager.GetString("HelpFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Due to limitations of the OCAD file format (in OCAD 10 and below), image objects will appear underneath courses and white out areas in the exported OCAD files. Please check the OCAD files to make sure your images appear as desired..
        /// </summary>
        internal static string ImagesMayAppearBadlyLayeredInOcad10Below {
            get {
                return ResourceManager.GetString("ImagesMayAppearBadlyLayeredInOcad10Below", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Landscape.
        /// </summary>
        internal static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leg {0} never reaches branch &apos;{1}&apos;: it was assigned to go a different way in a containing fork..
        /// </summary>
        internal static string LegAssignedOuterBranch {
            get {
                return ResourceManager.GetString("LegAssignedOuterBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leg {0} should be assigned to one of branches {1}.
        /// </summary>
        internal static string LegNotAssigned {
            get {
                return ResourceManager.GetString("LegNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Leg {0} is assigned to both branch &apos;{1}&apos; and branch &apos;{2}&apos;.
        /// </summary>
        internal static string LegUsedTwice {
            get {
                return ResourceManager.GetString("LegUsedTwice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Light Blue.
        /// </summary>
        internal static string LightBlue {
            get {
                return ResourceManager.GetString("LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The central control in the loop will be visited {0} times. There are {1} possible paths through the loops..
        /// </summary>
        internal static string LoopSummary {
            get {
                return ResourceManager.GetString("LoopSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mandatory crossing point.
        /// </summary>
        internal static string MandCrossing_Long {
            get {
                return ResourceManager.GetString("MandCrossing_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crossing.
        /// </summary>
        internal static string MandCrossing_Medium {
            get {
                return ResourceManager.GetString("MandCrossing_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a C.
        /// </summary>
        internal static string MandCrossing_Short {
            get {
                return ResourceManager.GetString("MandCrossing_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Map exchange.
        /// </summary>
        internal static string MapExchange_Long {
            get {
                return ResourceManager.GetString("MapExchange_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Exchange.
        /// </summary>
        internal static string MapExchange_Medium {
            get {
                return ResourceManager.GetString("MapExchange_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a MX.
        /// </summary>
        internal static string MapExchange_Short {
            get {
                return ResourceManager.GetString("MapExchange_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Another program has changed the map file &quot;{0}&quot;. Purple Pen will now reload the map..
        /// </summary>
        internal static string MapFileChanged {
            get {
                return ResourceManager.GetString("MapFileChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The map file &quot;{0}&quot; has been deleted. Please try to restore the map file, then press &quot;Ok&quot;..
        /// </summary>
        internal static string MapFileDeleted {
            get {
                return ResourceManager.GetString("MapFileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timed Start.
        /// </summary>
        internal static string MapIssue_Long {
            get {
                return ResourceManager.GetString("MapIssue_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Timed Start.
        /// </summary>
        internal static string MapIssue_Medium {
            get {
                return ResourceManager.GetString("MapIssue_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TS.
        /// </summary>
        internal static string MapIssue_Short {
            get {
                return ResourceManager.GetString("MapIssue_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All: {0}.
        /// </summary>
        internal static string Margins_All {
            get {
                return ResourceManager.GetString("Margins_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Left: {0}, Right: {1}, Top: {2}, Bottom: {3}.
        /// </summary>
        internal static string Margins_LRTB {
            get {
                return ResourceManager.GetString("Margins_LRTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The map file &quot;{0}&quot; could not be found.
        ///
        ///Most likely, the map file has been moved or deleted, or the Purple Pen file has been moved (possibly to a different computer). The map file must be present every time the Purple Pen event file is loaded. If you send a Purple Pen event file to another person, be sure that person has a copy of the map file also.
        ///
        ///After pressing OK, try to find a copy of the map file on your computer..
        /// </summary>
        internal static string MissingMapFile {
            get {
                return ResourceManager.GetString("MissingMapFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0} of Purple Pen is now available for download. (You are currently running version {1}.)
        ///
        ///Would you like to download and install the latest version?.
        /// </summary>
        internal static string NewerVersionAvailable {
            get {
                return ResourceManager.GetString("NewerVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Next &gt;.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No courses were selected to print..
        /// </summary>
        internal static string NoCoursesSelected {
            get {
                return ResourceManager.GetString("NoCoursesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No symbol.
        /// </summary>
        internal static string NoSymbol {
            get {
                return ResourceManager.GetString("NoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a All controls are used in a course..
        /// </summary>
        internal static string NoUnusedControls {
            get {
                return ResourceManager.GetString("NoUnusedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OCAD.
        /// </summary>
        internal static string OCAD {
            get {
                return ResourceManager.GetString("OCAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Open &quot;{0}&quot;.
        /// </summary>
        internal static string OpenLastEvent {
            get {
                return ResourceManager.GetString("OpenLastEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a OOM.
        /// </summary>
        internal static string OpenOrienteeringMapper {
            get {
                return ResourceManager.GetString("OpenOrienteeringMapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The page size is too small for any descriptions to be printed..
        /// </summary>
        internal static string PageTooSmall {
            get {
                return ResourceManager.GetString("PageTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Part {0}.
        /// </summary>
        internal static string PartN {
            get {
                return ResourceManager.GetString("PartN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Part {0} (of {1}).
        /// </summary>
        internal static string PartXOfY {
            get {
                return ResourceManager.GetString("PartXOfY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Finished printing &quot;{0}&quot;. Press OK to begin printing &quot;{1}&quot;..
        /// </summary>
        internal static string PausePrinting {
            get {
                return ResourceManager.GetString("PausePrinting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Pdfium PDF converter failed to read PDF file successfully.
        /// </summary>
        internal static string PdfConversionFailed {
            get {
                return ResourceManager.GetString("PdfConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PdfConverter.exe not found.
        /// </summary>
        internal static string PdfConverterNotFound {
            get {
                return ResourceManager.GetString("PdfConverterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PDF File|*.pdf.
        /// </summary>
        internal static string PdfFilter {
            get {
                return ResourceManager.GetString("PdfFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Map size from PDF.
        /// </summary>
        internal static string PdfMapSize {
            get {
                return ResourceManager.GetString("PdfMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Could not read result of PDF conversion from file &apos;{0}&apos;.
        /// </summary>
        internal static string PdfResultNotReadable {
            get {
                return ResourceManager.GetString("PdfResultNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a plural.
        /// </summary>
        internal static string Plural {
            get {
                return ResourceManager.GetString("Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Portrait.
        /// </summary>
        internal static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Printing page {0} (of {1}).
        /// </summary>
        internal static string PrintingPage {
            get {
                return ResourceManager.GetString("PrintingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Redo.
        /// </summary>
        internal static string RedoWithShortcut {
            get {
                return ResourceManager.GetString("RedoWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The customized text requires a &quot;*&quot; to indicate where the object being modified is placed..
        /// </summary>
        internal static string RequireStar {
            get {
                return ResourceManager.GetString("RequireStar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Do you want to save the changes you made to &apos;{0}&apos;?.
        /// </summary>
        internal static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a singular.
        /// </summary>
        internal static string Singular {
            get {
                return ResourceManager.GetString("Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a S.
        /// </summary>
        internal static string Start_Short {
            get {
                return ResourceManager.GetString("Start_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Too many total variations in this course. The number of distinct variations is limited to {0}..
        /// </summary>
        internal static string TooManyVariations {
            get {
                return ResourceManager.GetString("TooManyVariations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a *** If there exists a web site in the translated language that contains documentation for Purple Pen, enter the URL (including http) as the translation of this item. Otherwise leave it alone..
        /// </summary>
        internal static string TranslatedHelpWebSite {
            get {
                return ResourceManager.GetString("TranslatedHelpWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &amp;Undo.
        /// </summary>
        internal static string UndoWithShortcut {
            get {
                return ResourceManager.GetString("UndoWithShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a User Defined.
        /// </summary>
        internal static string UserDefined {
            get {
                return ResourceManager.GetString("UserDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A variation already exists at this control..
        /// </summary>
        internal static string VariationAlreadyExists {
            get {
                return ResourceManager.GetString("VariationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A control or leg must be selected to add a variation..
        /// </summary>
        internal static string VariationMustSelectControl {
            get {
                return ResourceManager.GetString("VariationMustSelectControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A variation cannot be added to a finish control..
        /// </summary>
        internal static string VariationNotFinish {
            get {
                return ResourceManager.GetString("VariationNotFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A variation cannot be added to the All Controls view..
        /// </summary>
        internal static string VariationNotInAllControls {
            get {
                return ResourceManager.GetString("VariationNotInAllControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A variation cannot be added to a score course..
        /// </summary>
        internal static string VariationNotInScoreCourse {
            get {
                return ResourceManager.GetString("VariationNotInScoreCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a A variation cannot be added to the last control. Add a finish control first..
        /// </summary>
        internal static string VariationNotLastControl {
            get {
                return ResourceManager.GetString("VariationNotLastControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Alpha {0}.
        /// </summary>
        internal static string Version_Alpha {
            get {
                return ResourceManager.GetString("Version_Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Beta {0}.
        /// </summary>
        internal static string Version_Beta {
            get {
                return ResourceManager.GetString("Version_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a RC {0}.
        /// </summary>
        internal static string Version_RC {
            get {
                return ResourceManager.GetString("Version_RC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Version {0}.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
